[package]
name = "verify-kayros-wasmx"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "Verify Kayros Provable WasmX app"

[lib]
crate-type = ["cdylib"]
path = "src/lib.rs"

[dependencies]
serde = { version = "1", features = ["derive"] }
provable-wasmx-core = { path = "../../core/wasmx" }
